sudo: required
services:
  - docker

before_install:  
  - docker build -t brinthasivakami/reactdockertravis -f Dockerfile.dev .

script:
  - docker run -e CI=true brinthasivakami/reactdockertravis npm run test -- --coverage